//Hardcoded language options to avoid unnecessary fetches
const languages = [
  { full: "Afrikaans", short: "af" },
  { full: "Albanian", short: "sq" },
  { full: "Amharic", short: "am" },
  { full: "Arabic", short: "ar" },
  { full: "Armenian", short: "hy" },
  { full: "Azerbaijani", short: "az" },
  { full: "Basque", short: "eu" },
  { full: "Belarusian", short: "be" },
  { full: "Bengali", short: "bn" },
  { full: "Bosnian", short: "bs" },
  { full: "Bulgarian", short: "bg" },
  { full: "Catalan", short: "ca" },
  { full: "Cebuano", short: "ceb" },
  { full: "Chinese (Simplified)", short: "zh-CN" },
  { full: "Chinese (Traditional)", short: "zh-TW" },
  { full: "Corsican", short: "co" },
  { full: "Croatian", short: "hr" },
  { full: "Czech", short: "cs" },
  { full: "Danish", short: "da" },
  { full: "Dutch", short: "nl" },
  { full: "English", short: "en" },
  { full: "Esperanto", short: "eo" },
  { full: "Estonian", short: "et" },
  { full: "Finnish", short: "fi" },
  { full: "French", short: "fr" },
  { full: "Frisian", short: "fy" },
  { full: "Galician", short: "gl" },
  { full: "Georgian", short: "ka" },
  { full: "German", short: "de" },
  { full: "Greek", short: "el" },
  { full: "Gujarati", short: "gu" },
  { full: "Haitian Creole", short: "ht" },
  { full: "Hausa", short: "ha" },
  { full: "Hawaiian", short: "haw" },
  { full: "Hebrew", short: "he" },
  { full: "Hindi", short: "hi" },
  { full: "Hmong", short: "hmn" },
  { full: "Hungarian", short: "hu" },
  { full: "Icelandic", short: "is" },
  { full: "Igbo", short: "ig" },
  { full: "Indonesian", short: "id" },
  { full: "Irish", short: "ga" },
  { full: "Italian", short: "it" },
  { full: "Japanese", short: "ja" },
  { full: "Javanese", short: "jv" },
  { full: "Kannada", short: "kn" },
  { full: "Kazakh", short: "kk" },
  { full: "Khmer", short: "km" },
  { full: "Kinyarwanda", short: "rw" },
  { full: "Korean", short: "ko" },
  { full: "Kurdish", short: "ku" },
  { full: "Kyrgyz", short: "ky" },
  { full: "Lao", short: "lo" },
  { full: "Latin", short: "la" },
  { full: "Latvian", short: "lv" },
  { full: "Lithuanian", short: "lt" },
  { full: "Luxembourgish", short: "lb" },
  { full: "Macedonian", short: "mk" },
  { full: "Malagasy", short: "mg" },
  { full: "Malay", short: "ms" },
  { full: "Malayalam", short: "ml" },
  { full: "Maltese", short: "mt" },
  { full: "Maori", short: "mi" },
  { full: "Marathi", short: "mr" },
  { full: "Mongolian", short: "mn" },
  { full: "Myanmar (Burmese)", short: "my" },
  { full: "Nepali", short: "ne" },
  { full: "Norwegian", short: "no" },
  { full: "Nyanja (Chichewa)", short: "ny" },
  { full: "Odia (Oriya)", short: "or" },
  { full: "Pashto", short: "ps" },
  { full: "Persian", short: "fa" },
  { full: "Polish", short: "pl" },
  { full: "Portuguese (Portugal, Brazil)", short: "pt" },
  { full: "Punjabi", short: "pa" },
  { full: "Romanian", short: "ro" },
  { full: "Russian", short: "ru" },
  { full: "Samoan", short: "sm" },
  { full: "Scots Gaelic", short: "gd" },
  { full: "Serbian", short: "sr" },
  { full: "Sesotho", short: "st" },
  { full: "Shona", short: "sn" },
  { full: "Sindhi", short: "sd" },
  { full: "Sinhala (Sinhalese)", short: "si" },
  { full: "Slovak", short: "sk" },
  { full: "Slovenian", short: "sl" },
  { full: "Somali", short: "so" },
  { full: "Spanish", short: "es" },
  { full: "Sundanese", short: "su" },
  { full: "Swahili", short: "sw" },
  { full: "Swedish", short: "sv" },
  { full: "Tagalog (Filipino)", short: "tl" },
  { full: "Tajik", short: "tg" },
  { full: "Tamil", short: "ta" },
  { full: "Tatar", short: "tt" },
  { full: "Telugu", short: "te" },
  { full: "Thai", short: "th" },
  { full: "Turkish", short: "tr" },
  { full: "Turkmen", short: "tk" },
  { full: "Ukrainian", short: "uk" },
  { full: "Urdu", short: "ur" },
  { full: "Uyghur", short: "ug" },
  { full: "Uzbek", short: "uz" },
  { full: "Vietnamese", short: "vi" },
  { full: "Welsh", short: "cy" },
  { full: "Xhosa", short: "xh" },
  { full: "Yiddish", short: "yi" },
  { full: "Yoruba", short: "yo" },
  { full: "Zulu", short: "zu" },
];

export default languages;
